// bootcamp/web/SPAs/github-react/src/github-search.jsx
import React, { useState } from 'react';

const GithubSearch = () => {
  const [username, setUserName] = useState('');
  const [githubUser, setGithubUser] = useState({});
  const [isLoadingUser, setIsLoadingUser] = useState(false);

  const getUser = () => {
    setIsLoadingUser(true);
    fetch(`https://api.github.com/users/${username}`)
      .then(response => {
        response.json().then(githubUser => {
          setGithubUser(githubUser);
          setIsLoadingUser(false);
        });
      })
      .catch(() => setIsLoadingUser(false));
  };

  return (
    <div>
      <h1>Hi, and welcome. Search by user below</h1>
      <input onChange={e => setUserName(e.currentTarget.value)}></input>
      <button onClick={() => getUser()}>Click me</button>
      {isLoadingUser ? <div className="spin"></div> : <React.Fragment />}
      {githubUser.login ? (
        <div className="card">
          <h2>{githubUser.login}</h2>

          <a href={githubUser.blog} style={{ display: 'block' }}>
            {githubUser.blog}
          </a>

          {githubUser.avatar_url ? <img src={githubUser.avatar_url} alt="avatar" width="200" height="200" /> : <React.Fragment />}
        </div>
      ) : (
        <React.Fragment />
      )}
    </div>
  );
};

export default GithubSearch;

// bootcamp/web/SPAs/github-angular/src/components/github-search.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { GithubResponse } from './githubResponse';

@Component({
  selector: 'app-github-search',
  templateUrl: './github-search.component.html',
  styleUrls: ['./github-search.component.scss']
})
export class GithubSearchComponent {
  username = '';
  githubUserInfo: GithubResponse = {} as any;
  loadingUser = false;

  constructor(private httpClient: HttpClient) {}

  getUser() {
    this.loadingUser = true;
    this.httpClient.get(`https://api.github.com/users/${this.username}`).subscribe(
      (response: GithubResponse) => {
        this.githubUserInfo = response;
        this.loadingUser = false;
      },
      (error: Error) => {
        this.loadingUser = false;
      }
    );
  }
}

<h1>
  Hi, and welcome. Search by user below
</h1>

<input [(ngModel)]="username" />

<button (click)="getUser()">Click me</button>

<div id="content">
  <div *ngIf="loadingUser" class="spin"></div>
  <div *ngIf="!loadingUser && githubUserInfo.login" class="card">
    <h2>{{ githubUserInfo.login }}</h2>

    <a [href]="githubUserInfo.blog" style="display: block">{{ githubUserInfo.blog }}</a>

    <img *ngIf="githubUserInfo.avatar_url" [src]="githubUserInfo.avatar_url" width="200" height="200" />
  </div>
</div>
